### ISSUE TITLE
Quality User Duplicate(?) Docs

### ISSUE THREAD

**Issue by davidphuong** [MarcFarmer/document-manager#39]
In the quality user's view who has been assigned to approve the document, the user sees the document in both "For approval" and "Draft". The following is the situation leading up to the bug:

1. Create a user and then create an organisation.
2. Create a new document and assign Bob (quality user) to be an approver.
3. Move document from draft to for approval stage.
4. Move document from approval stage to draft stage.
5. Log into Bob's account, Bob sees the document in both the "For approval" and "Draft" stage.

I'm assuming the correct behavior is that Bob sees the document only in the draft stage since the document has been moved back to draft.

**Comment by MarcFarmer** [comment]
#48
